import { SiteContent } from "./types";

export const defaultContent: SiteContent = {
  header: {
    logoUrl: "/assets/img/buildmetric-logo.png",
    phone: "+85 155 596 1658",
    email: "support@gmail.com",
    address: "Losangle, Street Road 24, New York, USA - 67452",
    workingHours: "Mon - Sat / 8am : 12pm",
    locationLink: "https://www.google.com/maps/place/Sri+Lanka",
    regionName: "Sri Lanka",
    regionFlagUrl: "https://flagcdn.com/w20/lk.png",
    ctaButtonText: "GET IN TOUCH",
    ctaButtonLink: "/contact",
    socialLinks: [
      { id: "soc-1", icon: "ri-facebook-fill", url: "https://www.facebook.com/" },
      { id: "soc-2", icon: "ri-twitter-x-fill", url: "https://www.twitter.com/" },
      { id: "soc-3", icon: "ri-instagram-line", url: "https://www.instagram.com/" },
      { id: "soc-4", icon: "ri-linkedin-fill", url: "https://www.linkedin.com/" },
    ],
    navLinks: [
      { id: "nav-1", label: "Home", url: "/" },
      { id: "nav-2", label: "About Us", url: "/about" },
      { id: "nav-3", label: "Services", url: "/service" },
      { id: "nav-4", label: "Projects", url: "/project" },
      { id: "nav-5", label: "Contact", url: "/contact" },
    ],
    languages: [
      { id: "lang-en", code: "EN", name: "English" },
      { id: "lang-ar", code: "AR", name: "العربية" },
    ],
  },
  homeHero: [
    {
      id: "slide-1",
      subtitle: "Our Vision",
      title: "Build Your Dream Buildings for Future",
      text: "We craft unique digital experiences. With more than 7 years of expertise we design and code clean websites.",
      bgImage: "/assets/img/hero/hero_bg_4_1.png",
      btnText: "Discover More",
      btnLink: "/about",
    },
    {
      id: "slide-2",
      subtitle: "High Quality Work",
      title: "Building the Future with Concrete Innovation",
      text: "Transforming ambitious visions into sustainable, world-class reality with our multi-disciplinary engineering specialists.",
      bgImage: "/assets/img/hero/hero_bg_4_2.png",
      btnText: "Our Services",
      btnLink: "/service",
    },
    {
      id: "slide-3",
      subtitle: "Best Solutions",
      title: "Engineering Excellence That Defines Tomorrow",
      text: "From strategic cost planning to comprehensive contract delivery, we safeguard every investment with precision.",
      bgImage: "/assets/img/hero/hero_bg_4_3.png",
      btnText: "Get in Touch",
      btnLink: "/contact",
    },
  ],
  homeCounter: [
    {
      id: "counter-1",
      number: 26,
      suffix: "k+",
      label: "Projects Completed",
    },
    {
      id: "counter-2",
      number: 98,
      suffix: "%",
      label: "Customers Satisfied",
    },
    {
      id: "counter-3",
      prefix: "$",
      number: 15,
      suffix: "B+",
      label: "Capital Projects Advised",
    },
    {
      id: "counter-4",
      number: 30,
      suffix: "+",
      label: "Years in Business",
    },
  ],
  homeAbout: {
    subtitle: "ABOUT US",
    title: "Specialist Construction Cost & Commercial Consultancy",
    desc1: "BuildMetric is a specialist construction cost and commercial consultancy delivering strategic Quantity Surveying, cost management, contract, claims and project advisory services.",
    desc2: "Drawing on extensive experience across complex residential, hospitality, commercial, marine and infrastructure developments, we provide independent, commercially focused advice throughout the project lifecycle.",
    experienceYears: 25,
    experienceLabel: "Years of Excellence",
    checklist: [
      "Providing Solutions For Construction, Management",
      "Engineers design and build the structure",
    ],
    missionTitle: "Our Mission",
    missionText: "We craft unique digital experiences. With more years of expertise we design.",
    visionTitle: "Our Vision",
    visionText: "Building the benchmark in commercial excellence and contractual integrity.",
    mainImage: "/assets/img/normal/about_1-1.png",
  },
  homeServices: [
    {
      id: "home-serv-1",
      num: "N.01",
      title: "Quantity Surveying & Cost Management",
      thumb: "/assets/img/service/service_thumb6_1.png",
      icon: "/assets/img/icon/service-icon2-1.svg",
      desc: "Strategic feasibility estimating, cost planning, BOQ preparation, tender evaluation, value engineering, and final accounts.",
    },
    {
      id: "home-serv-2",
      num: "N.02",
      title: "Commercial & Contract Management",
      thumb: "/assets/img/service/service_thumb6_2.png",
      icon: "/assets/img/icon/service-icon2-2.svg",
      desc: "Strategic contract administration, change management, variations control, commercial reporting, and contractual advice.",
    },
    {
      id: "home-serv-3",
      num: "N.03",
      title: "Claims & Dispute Support",
      thumb: "/assets/img/service/service_thumb6_3.png",
      icon: "/assets/img/icon/service-icon2-3.svg",
      desc: "Expert claims preparation, quantum assessment, EOT disruption commercial assessment, and dispute resolution.",
    },
    {
      id: "home-serv-4",
      num: "N.04",
      title: "Project Management / PMC",
      thumb: "/assets/img/service/service_thumb6_1.png",
      icon: "/assets/img/icon/service-icon2-4.svg",
      desc: "Robust project controls, procurement management, design coordination, risk management, and client reporting.",
    },
    {
      id: "home-serv-5",
      num: "N.05",
      title: "Development & Investment Advisory",
      thumb: "/assets/img/service/service_thumb6_2.png",
      icon: "/assets/img/icon/service-icon4-1.svg",
      desc: "Development feasibility, cost benchmarking, technical due diligence, CAPEX forecasting, and project monitoring.",
    },
    {
      id: "home-serv-6",
      num: "N.06",
      title: "Digital Project Commercial Management",
      thumb: "/assets/img/service/service_thumb6_3.png",
      icon: "/assets/img/icon/service-icon4-2.svg",
      desc: "Modern cost dashboards, digital cost controls, 5D BIM integration, and data-driven commercial intelligence.",
    },
  ],
  homeWhyChoose: [
    {
      id: "wcu-1",
      title: "Proven Track Record",
      desc: "Delivering multibillion-dollar residential, commercial, and marine infrastructures on time.",
      icon: "/assets/img/icon/why-icon1-1.svg",
    },
    {
      id: "wcu-2",
      title: "Contractual Mastery",
      desc: "Unrivaled expertise across FIDIC, NEC, and bespoke forms of building contract.",
      icon: "/assets/img/icon/why-icon1-2.svg",
    },
    {
      id: "wcu-3",
      title: "Data-Driven Precision",
      desc: "State-of-the-art cost models and predictive digital reporting benchmarks.",
      icon: "/assets/img/icon/why-icon1-3.svg",
    },
  ],
  homeProcess: [
    {
      id: "proc-1",
      number: "01",
      title: "Feasibility & Planning",
      desc: "Initial strategic cost modeling and risk analysis to establish watertight foundations.",
    },
    {
      id: "proc-2",
      number: "02",
      title: "Design & Procurement",
      desc: "Rigorous BOQ drafting, value engineering, and competitive tender evaluation.",
    },
    {
      id: "proc-3",
      number: "03",
      title: "Delivery & Close-Out",
      desc: "Disciplined contract administration, variation governance, and equitable final accounts.",
    },
  ],
  homePortfolio: [
    {
      id: "port-1",
      title: "Breakwater, Dredging & Wharf Works",
      category: "Marine & Infrastructure",
      image: "/assets/img/project/project2_1.png",
    },
    {
      id: "port-2",
      title: "The Villa – 1,200+ Residences",
      category: "Residential Development",
      image: "/assets/img/project/project2_5.png",
    },
    {
      id: "port-3",
      title: "78-Storied High-Rise Tower",
      category: "Commercial & Mix-Use",
      image: "/assets/img/project/project2_9.png",
    },
  ],
  homeTestimonials: [
    {
      id: "test-1",
      name: "Arthur Pendelton",
      role: "Managing Director, Apex Properties",
      rating: 5,
      text: "BuildMetric protected our margins across a 3-year luxury hospitality build. Their claims handling and variation audits saved us millions.",
      avatar: "/assets/img/testimonial/testi_1_1.png",
    },
    {
      id: "test-2",
      name: "Mariam Al-Mansoor",
      role: "Chief Commercial Officer, Gulf Horizon",
      rating: 5,
      text: "Their precision in Bills of Quantities and tender evaluations brought complete clarity and confidence to our board of investors.",
      avatar: "/assets/img/testimonial/testi_1_2.png",
    },
  ],
  ctaFour: {
    subtitle: "We have won many industry awards",
    title1: "Your Renovation",
    title2: "Starts Here",
    bgImage: "/assets/img/bg/cta-bg4-1.png",
    btnText: "Get in Touch",
    btnLink: "/contact",
  },
  aboutPage: {
    breadcrumb: {
      title: "About Us",
      pageName: "About Us",
      bgImage: "/assets/img/bg/breadcumb-bg.png",
    },
    subtitle: "ABOUT US",
    title: "WE BUILDING EVERYTHING THAT YOU NEEDED",
    desc1: "BuildMetric is a specialist construction cost and commercial consultancy delivering strategic Quantity Surveying, cost management, contract, claims and project advisory services.",
    desc2: "Drawing on extensive experience across complex residential, hospitality, commercial, marine and infrastructure developments, we provide independent, commercially focused advice throughout the project lifecycle.",
    experienceYears: 40,
    experienceLabel: "Business Experience",
    checklist: [
      "Providing Solutions For Construction, Management",
      "Engineers design and build the structure",
    ],
    mainImage: "/assets/img/normal/about_2-1.png",
    whyChooseSubtitle: "Why Choose Us",
    whyChooseTitle: "High Quality Innovate Design",
    whyChooseCards: [
      {
        id: "wcc-1",
        title: "Technology",
        desc: "We are expert your all work is very nice waiting for next project.",
        icon: "/assets/img/icon/why-icon1-1.svg",
      },
      {
        id: "wcc-2",
        title: "Core Planning",
        desc: "All the Lorem Ipsum generators on the Internet tend to repeat predefined.",
        icon: "/assets/img/icon/why-icon1-2.svg",
      },
      {
        id: "wcc-3",
        title: "Project Result",
        desc: "Making this the first true generator on the Internet uses a dictionary.",
        icon: "/assets/img/icon/why-icon1-3.svg",
      },
      {
        id: "wcc-4",
        title: "Quality Assurance",
        desc: "Rigorous quality checks and international standards compliance.",
        icon: "/assets/img/icon/why-icon1-4.svg",
      },
    ],
    processSubtitle: "Work Process",
    processTitle: "How We Complete Our Projects",
    processSteps: [
      {
        id: "about-proc-1",
        number: "01",
        title: "Project Research",
        desc: "Comprehensive early analysis and site evaluation.",
      },
      {
        id: "about-proc-2",
        number: "02",
        title: "Planning & Design",
        desc: "Collaborative design coordination and scheduling.",
      },
      {
        id: "about-proc-3",
        number: "03",
        title: "Execution & Delivery",
        desc: "Flawless site delivery and client handover.",
      },
    ],
  },
  servicesPage: {
    breadcrumb: {
      title: "Services",
      pageName: "Services",
      bgImage: "/assets/img/bg/breadcumb-bg.png",
    },
    subtitle: "What We Do",
    title: "Our services that we provide",
    description: "Comprehensive commercial, cost, contract, and project management solutions tailored for excellence",
    services: [
      {
        id: "srv-card-1",
        num: "01",
        title: "Quantity Surveying & Cost Management",
        icon: "/assets/img/icon/service-icon1-1.png",
        items: [
          "Feasibility estimates",
          "Cost planning",
          "BOQ preparation",
          "Tender documentation",
          "Tender evaluation",
          "Value engineering",
          "Final accounts",
        ],
      },
      {
        id: "srv-card-2",
        num: "02",
        title: "Commercial & Contract Management",
        icon: "/assets/img/icon/service-icon1-2.png",
        items: [
          "Contract administration",
          "Change management",
          "Variations",
          "Commercial reporting",
          "Payment certification",
          "Contractual advice",
        ],
      },
      {
        id: "srv-card-3",
        num: "03",
        title: "Claims & Dispute Support",
        icon: "/assets/img/icon/service-icon1-3.png",
        items: [
          "Claims preparation/review",
          "Quantum assessment and expert witness report preparation",
          "EOT/disruption commercial assessment",
          "Negotiation support",
          "Arbitration/adjudication support",
        ],
      },
      {
        id: "srv-card-4",
        num: "04",
        title: "Project Management / PMC",
        icon: "/assets/img/icon/service-icon1-4.png",
        items: [
          "Project controls",
          "Procurement management",
          "Design coordination",
          "Risk management",
          "Reporting",
        ],
      },
      {
        id: "srv-card-5",
        num: "05",
        title: "Development & Investment Advisory",
        icon: "/assets/img/icon/service-icon1-5.png",
        items: [
          "Development feasibility",
          "Cost benchmarking",
          "Due diligence",
          "CAPEX forecasting",
          "Development monitoring",
        ],
      },
      {
        id: "srv-card-6",
        num: "06",
        title: "Digital Project Commercial Management",
        icon: "/assets/img/icon/service-icon1-6.png",
        items: [
          "Cost dashboards",
          "Digital cost control",
          "BIM/5D integration",
          "Data-driven and AI-integrated commercial reporting",
        ],
      },
    ],
    benefitsSubtitle: "Our Benefits",
    benefitsTitle: "Why choose us",
    benefitsThumb: "/assets/img/normal/process-thumb2-1.png",
    benefitsList: [
      {
        id: "ben-1",
        number: "01",
        title: "Advanced Technology",
        desc: "We craft unique digital experiences. With more years of expertise we design.",
      },
      {
        id: "ben-2",
        number: "02",
        title: "Trusted Company",
        desc: "We craft unique digital experiences. With more years of expertise we design.",
      },
      {
        id: "ben-3",
        number: "03",
        title: "Professional Teams",
        desc: "We craft unique digital experiences. With more years of expertise we design.",
      },
      {
        id: "ben-4",
        number: "04",
        title: "Stylistic formula method",
        desc: "We craft unique digital experiences. With more years of expertise we design.",
      },
    ],
  },
  serviceDetailsList: [
    {
      id: "service-tab-1",
      num: "01",
      tabTitle: "Quantity Surveying & Cost Management",
      serviceTitle: "Quantity Surveying & Cost Management",
      thumb: "/assets/img/why/why-tab-thumb3-1.png",
      desc: "We deliver strategic Quantity Surveying and end-to-end Cost Management solutions designed to safeguard your capital investment, maximize cost efficiency, and provide complete commercial transparency across all project phases.",
      subsections: [
        { name: "Feasibility estimates", detail: "Comprehensive early-stage cost modeling and high-level budget frameworks to assess commercial viability before commitment." },
        { name: "Cost planning", detail: "Detailed elemental cost planning, benchmarked budgeting, and disciplined cost control from concept design to procurement." },
        { name: "BOQ preparation", detail: "Meticulous Bills of Quantities prepared strictly in compliance with standard methods of measurement (POMI, NRM, CESSM)." },
        { name: "Tender documentation", detail: "Robust, watertight tender packages including pricing schedules, specifications alignment, and tender instructions." },
        { name: "Tender evaluation", detail: "Rigorous commercial and technical bid analysis, normalized rate comparisons, and definitive procurement recommendations." },
        { name: "Value engineering", detail: "Proactive identification of functional cost-saving alternatives and lifecycle optimizations without sacrificing design quality." },
        { name: "Final accounts", detail: "Structured commercial close-out, valuation of variations, re-measurement verification, and equitable final account settlements." },
      ],
    },
    {
      id: "service-tab-2",
      num: "02",
      tabTitle: "Commercial & Contract Management",
      serviceTitle: "Commercial & Contract Management",
      thumb: "/assets/img/why/why-tab-thumb3-2.png",
      desc: "Our commercial and contract management consultancy protects your contractual rights, mitigates commercial exposure, and ensures compliance with conditions of contract across FIDIC, NEC, and bespoke forms.",
      subsections: [
        { name: "Contract administration", detail: "Comprehensive day-to-day contractual governance, notices compliance, formal correspondence, and obligations management." },
        { name: "Change management", detail: "Standardized protocols to identify, log, assess, and manage design or scope changes before cost commitments occur." },
        { name: "Variations", detail: "Definitive measurement, contractual justification, and fair valuation of contract variations and compensation events." },
        { name: "Commercial reporting", detail: "Insightful monthly cost value reconciliations (CVR), cash flow forecasts, and senior leadership commercial dashboards." },
        { name: "Payment certification", detail: "Rigorous interim valuation assessments, progress verification, off-site materials checks, and payment certificate issuance." },
        { name: "Contractual advice", detail: "Strategic advisory on risk allocation, contract interpretation, liability clauses, and proactive conflict avoidance." },
      ],
    },
    {
      id: "service-tab-3",
      num: "03",
      tabTitle: "Claims & Dispute Support",
      serviceTitle: "Claims & Dispute Support",
      thumb: "/assets/img/why/why-tab-thumb3-3.png",
      desc: "We provide authoritative claims analysis, delay quantum evaluation, and robust dispute resolution advisory to resolve construction disputes efficiently and substantiate client entitlements.",
      subsections: [
        { name: "Claims preparation/review", detail: "Forensic compilation, defense, or audit of contractual delay, disruption, acceleration, and additional cost claims." },
        { name: "Quantum assessment and expert witness report preparation", detail: "Evidence-backed independent quantum calculations, cost audits, and credible expert witness reports for legal proceedings." },
        { name: "EOT/disruption commercial assessment", detail: "Detailed extension of time (EOT) commercial assessments and measured mile disruption analysis to substantiate financial impact." },
        { name: "Negotiation support", detail: "High-level commercial negotiation strategy, mediation assistance, and settlement structuring to avoid protracted litigation." },
        { name: "Arbitration/adjudication support", detail: "End-to-end technical and commercial support to legal counsel during statutory adjudication, arbitration, or litigation hearings." },
      ],
    },
    {
      id: "service-tab-4",
      num: "04",
      tabTitle: "Project Management / PMC",
      serviceTitle: "Project Management / PMC",
      thumb: "/assets/img/why/why-tab-thumb3-4.png",
      desc: "End-to-end project management and project management consultancy (PMC) ensuring your projects are delivered on time, within budget, and to the highest standards of safety and quality.",
      subsections: [
        { name: "Project controls", detail: "Integrated baseline scheduling, earned value management (EVM), critical path monitoring, and cost tracking systems." },
        { name: "Procurement management", detail: "Developing customized procurement strategies, pre-qualifying contractors, and orchestrating strategic supply chain engagement." },
        { name: "Design coordination", detail: "Cross-disciplinary design management, constructability reviews, and alignment between design consultants and contractors." },
        { name: "Risk management", detail: "Quantitative and qualitative risk registers, scenario modeling, mitigation plans, and contingency governance." },
        { name: "Reporting", detail: "Transparent executive project reports, KPI tracking, photographic milestones, and proactive issue escalation." },
      ],
    },
    {
      id: "service-tab-5",
      num: "05",
      tabTitle: "Development & Investment Advisory",
      serviceTitle: "Development & Investment Advisory",
      thumb: "/assets/img/why/why-tab-thumb3-5.png",
      desc: "Strategic development advisory offering real estate investors, developers, and financial institutions authoritative data to assess risk, forecast capital requirements, and protect investments.",
      subsections: [
        { name: "Development feasibility", detail: "Rigorous appraisal of project economics, development residual appraisals, and market sensitivity modeling." },
        { name: "Cost benchmarking", detail: "Access to verified historical data and industry indices to benchmark cost-per-square-meter across building typologies." },
        { name: "Due diligence", detail: "Independent technical and commercial due diligence audits to identify risks prior to land acquisition or funding commitment." },
        { name: "CAPEX forecasting", detail: "Strategic whole-life capital expenditure profiles, replacement reserve modeling, and operational cost projections." },
        { name: "Development monitoring", detail: "Independent lender supervisor and fund monitoring, tracking drawdowns against verified site construction progress." },
      ],
    },
    {
      id: "service-tab-6",
      num: "06",
      tabTitle: "Digital Project Commercial Management",
      serviceTitle: "Digital Project Commercial Management",
      thumb: "/assets/img/why/why-tab-thumb3-6.png",
      desc: "Leveraging digital workflows, BIM 5D cost integration, and AI-enabled data analytics to modernize construction commercial governance and enhance decision-making certainty.",
      subsections: [
        { name: "Cost dashboards", detail: "Interactive, real-time PowerBI and digital cost reporting dashboards providing live visibility of project financial metrics." },
        { name: "Digital cost control", detail: "Cloud-based cost management systems that streamline approvals, variations logs, and collaborative financial workflows." },
        { name: "BIM/5D integration", detail: "Linking 3D digital design models with cost and schedule parameters (5D) for automated quantity takeoffs and clash cost impact." },
        { name: "Data-driven and AI-integrated commercial reporting", detail: "Harnessing historical cost analytics, predictive cost algorithms, and automated commercial compliance checks." },
      ],
    },
  ],
  projectsPage: {
    breadcrumb: {
      title: "Projects",
      pageName: "Projects",
      bgImage: "/assets/img/bg/breadcumb-bg.png",
    },
    projects: [
      {
        id: "proj-1",
        title: "Breakwater, Dredging, Wharf & Reclamation Works",
        location: "Western Region, Abu Dhabi, UAE",
        image: "/assets/img/project/project2_1.png",
      },
      {
        id: "proj-2",
        title: "Coastal Revetment Works",
        location: "Western Region, Abu Dhabi, UAE",
        image: "/assets/img/project/project2_2.png",
      },
      {
        id: "proj-3",
        title: "Site Grading, Roads & Paving Works",
        location: "Western Region, Abu Dhabi, UAE",
        image: "/assets/img/project/project2_3.png",
      },
      {
        id: "proj-4",
        title: "Composite Mid-Rise Building Development",
        location: "Western Region, Abu Dhabi, UAE",
        image: "/assets/img/project/project2_4.png",
      },
      {
        id: "proj-5",
        title: "The Villa – Thematic Residential Development",
        location: "Dubai, UAE – 1,200+ villas",
        image: "/assets/img/project/project2_5.png",
      },
      {
        id: "proj-6",
        title: "Al Khail Gate – Phase 1",
        location: "Dubai, UAE",
        image: "/assets/img/project/project2_6.png",
      },
      {
        id: "proj-7",
        title: "DubaiLand Master Development",
        location: "Dubai, UAE",
        image: "/assets/img/project/project2_7.png",
      },
      {
        id: "proj-8",
        title: "High-End Private Residential / Palace Developments",
        location: "UAE",
        image: "/assets/img/project/project2_8.png",
      },
      {
        id: "proj-9",
        title: "78 storied high-rise building (mix use)",
        location: "Dubai, UAE",
        image: "/assets/img/project/project2_9.png",
      },
    ],
  },
  projectDetails: {
    breadcrumb: {
      title: "Project Details",
      pageName: "Project Details",
      bgImage: "/assets/img/bg/breadcumb-bg.png",
    },
    mainImage: "/assets/img/project/project_details1_1.png",
    projectInfo: {
      client: "Rebecca Tylor",
      category: "Building & Commercial",
      location: "Abu Dhabi & Dubai, UAE",
      date: "12 January, 2024",
      status: "Completed",
      budget: "$200,560,000",
    },
    specs: [
      { id: "spec-1", label: "Client", value: "Rebecca Tylor / Emaar Group" },
      { id: "spec-2", label: "Category", value: "Building & Commercial Infrastructure" },
      { id: "spec-3", label: "Location", value: "Abu Dhabi & Dubai, UAE" },
      { id: "spec-4", label: "Date", value: "12 January, 2024" },
      { id: "spec-5", label: "Status", value: "Completed & Handed Over" },
      { id: "spec-6", label: "Budget", value: "$200,560,000 USD" },
    ],
    overviewTitle: "Project Overview",
    overviewText: "BuildMetric delivered full commercial advisory, quantity surveying and independent cost management for this landmark development, ensuring strict compliance with budgetary constraints and timeline milestones.",
    featureHighlights: [
      {
        id: "feat-1",
        title: "Full Principal Contractor service",
        desc: "Comprehensive site execution and supervisory governance.",
        icon: "/assets/img/icon/service-icon1-1.png",
      },
      {
        id: "feat-2",
        title: "Cost Engineering & Measurement",
        desc: "Meticulous valuation of variation claims and certified progress.",
        icon: "/assets/img/icon/service-icon1-2.png",
      },
      {
        id: "feat-3",
        title: "Commercial Close-out",
        desc: "Seamless final accounts agreement with zero unresolved disputes.",
        icon: "/assets/img/icon/service-icon1-3.png",
      },
    ],
    challengesTitle: "Challenges & Strategic Solutions",
    challengesText: "Through proactive value engineering and disciplined change management, the team resolved complex geotechnical challenges without compromising design intent or escalating the target budget.",
  },
  contactPage: {
    breadcrumb: {
      title: "Contact Us",
      pageName: "Contact Us",
      bgImage: "/assets/img/bg/breadcumb-bg.png",
    },
    offices: [
      {
        id: "office-1",
        title: "Main Office - Sri Lanka",
        phone: "+94 11 234 5678",
        email: "srilanka@buildmetric.com",
        hours: "Mon - Sat 08.00 - 18.00",
        thumb: "/assets/img/normal/contact_page1-1.png",
      },
      {
        id: "office-2",
        title: "Middle East Hub - UAE",
        phone: "+971 4 567 8900",
        email: "uae@buildmetric.com",
        hours: "Sun - Thu 08.00 - 18.00",
        thumb: "/assets/img/normal/contact_page1-2.png",
      },
      {
        id: "office-3",
        title: "London Office",
        phone: "+44 20 7946 0912",
        email: "london@buildmetric.com",
        hours: "Mon - Fri 09.00 - 17.00",
        thumb: "/assets/img/normal/contact_page1-3.png",
      },
    ],
    formSubtitle: "GET IN TOUCH",
    formTitle: "Have An Upcoming Project? Let's Discuss",
    formDesc: "Reach out to our specialist Quantity Surveyors and Commercial Directors for an initial consultation.",
    submitButtonText: "SEND MESSAGE NOW",
    mapEmbedUrl: "https://maps.google.com/maps?q=Colombo,%20Sri%20Lanka&t=&z=13&ie=UTF8&iwloc=&output=embed",
  },
  footer: {
    aboutText: "BuildMetric is a specialist construction cost and commercial consultancy delivering strategic Quantity Surveying, cost management, contract, claims and project advisory services.",
    phone: "+85 155 596 1658",
    email: "support@gmail.com",
    address: "Losangle, Street Road 24, New York, USA - 67452",
    workingHours: "Monday - Friday: 08:00 - 18:00",
    copyrightText: "© 2026 BuildMetric Consultancy. All Rights Reserved.",
    quickLinks: [
      { id: "ql-1", label: "Home", url: "/" },
      { id: "ql-2", label: "About Us", url: "/about" },
      { id: "ql-3", label: "Services", url: "/service" },
      { id: "ql-4", label: "Projects", url: "/project" },
      { id: "ql-5", label: "Contact Us", url: "/contact" },
    ],
  },
};
